### ISSUE TITLE
How to add an admin player automatically

### ISSUE THREAD

**Issue by crashzk** [deaFPS/cs2-pug-lua#7]
I tried adding my SteamID3 to the `whitelist.lua` file and even editing the admins in the `dea.lua` file:

https://github.com/deaFPS/cs2-pug-lua/blob/0ae3f6e5cfd199f406cc66018a4b507551c483dd/scripts/vscripts/dea.lua#L12C1-L19C2

But without success, every time I log in I have to use `adminlogin` to be able to use the commands.

Is there any way to automatically add this access to my Steam, so I just go in and use the commands?

**Comment by deaFPS** [comment]
sadly for that to work i would need to use a very convoluted method of storing steamid and merging them with the player entities (which i can fetch when a player uses a command), since when using a command the api i unable to return a steamid of the command user... even after all that it would break after stuff like map change since to fetch the steamid in lua we have to use the player_connect event which doesn't get triggered on map reload... we need to refetch the ids since the plugin will reload on map change

using a adminlogin was the easier solution in my eyes using LUA, hopefully once pulse replaces lua there will be a less convoluted solution

alternatively you as the admin can bind a key to login

`bind "L" "adminlogin 123"`
